build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related prod APIs"
  contactDetails:
    name: "Samson - Product Owner"
    email: "samson@gmail.com"
  onCallSupport:
    -(555) 555-1443
    -(555) 523-1746